# Base configs
baseurl: "forsithias.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Ram Patra"
subtitle: "See the world through my eyes!"
author: "Ram Patra"
header:
 title: "Photography"
 subtitle: "by Ram Patra"
footer:
 name: "Hey there, my name is Ram"
 bio: "From Toronto."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ramswarooppatra"
  instagram: "https://www.instagram.com/ramswarooppatra"
  dribbble: "https://dribbble.com/ramswaroop"
  linkedin: "https://in.linkedin.com/in/ramswarooppatra"
  github: "https://www.github.com/ramswaroop"
